name: Pre Release

on:
  push:
    branches: [ "master" ]
  pull_request: # only for testing
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  pre-release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup environment variables
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
        
    - name: Copy Distributables
      shell: bash
      run: |
        mkdir final
        mkdir final/bin
        mv dist/* final/bin

    - name: Configure CMake
      run: cmake -A Win32 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/final -DD2BS_VERSION="${{ env.sha_short }}"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{ github.workspace }}/final --config ${{env.BUILD_TYPE}}

    - name: Package
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        directory: ${{ github.workspace }}/final/bin
        filename: d2bs-${{ env.sha_short }}.zip

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Pre-release Build"
        files: |
          final/bin/d2bs-${{ env.sha_short }}.zip