name: Pre Release

on:
  push:
    branches: [ "master" ]

env:
  GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")
  BUILD_TYPE: RelWithDebInfo
  INSTALL_PREFIX: ${{github.workspace}}/final

jobs:
  pre-release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -A Win32 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PREFIX}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{env.INSTALL_PREFIX}} --config ${{env.BUILD_TYPE}}

    - name: Package
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        directory: ${{github.workspace}}
        path: final/bin/*
        filename: "d2bs-${{env.GIT_HASH}}"

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: "latest"
        prerelease: true
        title: "Pre-release Build"
        files: |
          d2bs-${{env.GIT_HASH}}.zip