name: Tagged release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  BUILD_TYPE: Release
  INSTALL_PREFIX: ${{github.workspace}}/final

jobs:
  pre-release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup environment variables
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"

    - name: Configure CMake
      run: cmake -A Win32 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PREFIX}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{env.INSTALL_PREFIX}} --config ${{env.BUILD_TYPE}}

    - name: Package
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        directory: ${{ env.INSTALL_PREFIX }}/bin
        filename: "d2bs-${{ github.ref_name }}.zip"

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ github.ref_name }}"
        prerelease: false
        title: ${{ github.ref_name }}
        files: |
          ${{ env.INSTALL_PREFIX }}/bin/d2bs-${{ github.ref_name }}.zip